### ISSUE TITLE
Error on keystone init

### ISSUE THREAD

**Issue by ericjang96** [UBC-LFS/lfs-agrifood-cms#4]
I cloned the repo to a new PC, and `node keystone` returned this error to me:
```
------------------------------------------------

UBC AgriFood Database Project: Update 0.0.1-admins failed with errors:

ValidationError: Path `institution` is required.


------------------------------------------------
An error occurred applying updates, bailing on Keystone init.

Error details:
ValidationError: Path `institution` is required.
```

I'm pretty sure what's happening is that `institution` was added as a required field for the `User` model a while ago. So when `keystone init` tries to add the default admin user, it fails because no institution is provided. This probably has gone unnoticed because we keep reusing the same MongoDB database, so `init` is never called.

As expected, this error disappears when I remove the `required: true` part from the `User` model, but I'm guessing @soohyunkim put it as a required field to prevent new users from signing up without specifying their institution.

**Comment by soohyunkim** [comment]
Should I remove the `institution` from being a required field? Or should I add the path to init? @ericjang96

**Comment by ericjang96** [comment]
The `user` isn't the required field, `institution` is a required field for `user`, but the default keystone init file doesn't know that, so it doesn't provide one. It's up to you if you want to remove `institution` from being required, or to modify the init file to provide some default institution. Maybe it makes sense to not make this a required field, since it shouldn't matter what `institution` an admin user belongs to.
